using System.Globalization;

namespace AnywhereLLM.Services;

/// en/ko string table (ports Resources/*.lproj/Localizable.strings). Format
/// placeholders were rewritten from %@/%d to .NET composite format {0}/{1}.
/// L() picks ko when the current UI culture is Korean, else en (matching the
/// Swift NSLocalizedString fallback behavior).
public static class Loc
{
    private static readonly bool Ko =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ko", StringComparison.OrdinalIgnoreCase);

    public static string L(string key)
        => (Ko ? Korean : English).TryGetValue(key, out var v) ? v
         : English.TryGetValue(key, out var e) ? e : key;

    public static string L(string key, params object[] args)
        => string.Format(L(key), args);

    private static readonly Dictionary<string, string> English = new()
    {
        ["input.ask"] = "Ask anything… (⏎ send, ⇧⏎ newline, Esc close)",
        ["input.instructFirst"] = "Enter instructions — empty ⏎ sends the prompt alone (Esc close)",
        ["input.instruct"] = "Enter instructions… (⏎ send, ⇧⏎ newline, Esc close)",
        ["panel.generating"] = "Generating…",
        ["panel.replace"] = "Replace (Ctrl+⏎)",
        ["panel.insert"] = "Insert (Ctrl+⏎)",
        ["prompt.appContext"] = "The user is writing text in the \"{0}\" app.",
        ["prompt.viewOnly"] = "Your answer is shown to the user in a panel. Answer the request concisely and accurately.",
        ["prompt.editSelection"] = "Edit the user's selected text according to the instructions. Output only the text that replaces the selection — no explanations or greetings.",
        ["prompt.insertAtCursor"] = "Output only the text to insert at the cursor position — no explanations or greetings.",
        ["prompt.sectionSelection"] = "[Selected text]",
        ["prompt.sectionFullText"] = "[Full field content]",
        ["prompt.sectionRequest"] = "[Request]",
        ["settings.windowTitle"] = "AnywhereLLM Settings",
        ["settings.apiKey"] = "API Key",
        ["settings.model"] = "Model",
        ["settings.fetching"] = "Fetching…",
        ["settings.fetchModels"] = "Fetch Models",
        ["settings.fetchedModels"] = "Fetched Models",
        ["settings.emptyModelList"] = "The model list is empty.",
        ["settings.disableThink"] = "Disable think mode",
        ["settings.disableThinkHelp"] = "Disables the thinking phase of reasoning models (Qwen3.5, Gemma 4, etc.) at request time. Ollama is switched to its native API for full suppression. Turn this off if an unsupported server (e.g. OpenAI) returns errors. The <think> output filter is always active.",
        ["settings.behavior"] = "Behavior",
        ["settings.applyMode"] = "Apply Results",
        ["settings.applyPreview"] = "Preview, then confirm",
        ["settings.applyImmediate"] = "Apply immediately",
        ["settings.panelPosition"] = "Panel Position",
        ["settings.positionCaret"] = "Follow caret",
        ["settings.positionMouse"] = "At mouse pointer",
        ["settings.positionCenter"] = "Screen center",
        ["settings.context"] = "Context",
        ["settings.includeAppName"] = "Include target app name",
        ["settings.includeFullText"] = "Include full field content",
        ["settings.fullTextWarning"] = "The focused field's entire content is sent to the API.",
        ["settings.cleartextKeyWarning"] = "This endpoint uses plain HTTP — your API key is sent unencrypted and can be read by others on the network.",
        ["settings.systemPrompt"] = "System Prompt",
        ["settings.profile"] = "Profile",
        ["settings.add"] = "Add",
        ["settings.rename"] = "Rename",
        ["settings.delete"] = "Delete",
        ["settings.newProfile"] = "New Profile",
        ["settings.defaultProfile"] = "Default",
        ["settings.profileName"] = "Profile Name",
        ["settings.hotkey"] = "Hotkey",
        ["settings.recordingKeys"] = "Waiting for keys…",
        ["settings.record"] = "Record",
        ["settings.system"] = "System",
        ["settings.launchAtLogin"] = "Launch at login",
        ["common.ok"] = "OK",
        ["common.cancel"] = "Cancel",
        ["error.invalidBaseURL"] = "Invalid Base URL: {0}",
        ["error.httpFailure"] = "LLM request failed (HTTP {0}): {1}",
        ["error.invalidResponse"] = "Invalid response",
        ["error.unknown"] = "Unknown error",
        ["error.truncatedStream"] = "The response was cut off before completing.",
        ["app.secureFieldBlocked"] = "Secure field blocked",
        ["hotkey.conflictTitle"] = "Hotkey unavailable",
        ["hotkey.conflictMessage"] = "That key combination is already in use by another app. The previous hotkey has been kept. Pick a different combination in Settings.",
        ["menu.settings"] = "Settings…",
        ["menu.build"] = "Build {0}",
        ["menu.quit"] = "Quit",
    };

    private static readonly Dictionary<string, string> Korean = new()
    {
        ["input.ask"] = "무엇이든 물어보세요… (⏎ 전송, ⇧⏎ 줄바꿈, Esc 닫기)",
        ["input.instructFirst"] = "지시 입력 — 비워둔 채 ⏎면 프롬프트만으로 요청 (Esc 닫기)",
        ["input.instruct"] = "지시를 입력하세요… (⏎ 전송, ⇧⏎ 줄바꿈, Esc 닫기)",
        ["panel.generating"] = "생성 중…",
        ["panel.replace"] = "교체 (Ctrl+⏎)",
        ["panel.insert"] = "삽입 (Ctrl+⏎)",
        ["prompt.appContext"] = "사용자는 \"{0}\" 앱에서 텍스트를 작성 중입니다.",
        ["prompt.viewOnly"] = "답변은 사용자에게 패널로 표시됩니다. 요청에 간결하고 정확하게 답하세요.",
        ["prompt.editSelection"] = "사용자가 선택한 텍스트를 지시에 따라 편집하세요. 결과는 선택 영역을 대체할 텍스트만 출력하고, 설명이나 인사말은 넣지 마세요.",
        ["prompt.insertAtCursor"] = "결과는 커서 위치에 삽입될 텍스트만 출력하고, 설명이나 인사말은 넣지 마세요.",
        ["prompt.sectionSelection"] = "[선택한 텍스트]",
        ["prompt.sectionFullText"] = "[현재 필드 전체 내용]",
        ["prompt.sectionRequest"] = "[요청]",
        ["settings.windowTitle"] = "AnywhereLLM 설정",
        ["settings.apiKey"] = "API 키",
        ["settings.model"] = "모델",
        ["settings.fetching"] = "가져오는 중…",
        ["settings.fetchModels"] = "모델 가져오기",
        ["settings.fetchedModels"] = "가져온 모델",
        ["settings.emptyModelList"] = "모델 목록이 비어 있습니다.",
        ["settings.disableThink"] = "생각(think) 모드 끄기",
        ["settings.disableThinkHelp"] = "Qwen3.5/Gemma 4 등 reasoning 모델의 생각 과정을 요청 단계에서 끕니다. Ollama는 네이티브 API로 자동 전환해 완전 차단합니다. 미지원 서버(OpenAI 등)에서 오류가 나면 끄세요. <think> 출력 필터는 항상 동작합니다.",
        ["settings.behavior"] = "동작",
        ["settings.applyMode"] = "결과 반영",
        ["settings.applyPreview"] = "미리보기 후 확정",
        ["settings.applyImmediate"] = "즉시 반영",
        ["settings.panelPosition"] = "패널 위치",
        ["settings.positionCaret"] = "캐럿 추적",
        ["settings.positionMouse"] = "마우스 위치",
        ["settings.positionCenter"] = "화면 중앙",
        ["settings.context"] = "컨텍스트",
        ["settings.includeAppName"] = "대상 앱 이름 포함",
        ["settings.includeFullText"] = "필드 전체 내용 포함",
        ["settings.fullTextWarning"] = "포커스된 필드 전체 내용이 API로 전송됩니다.",
        ["settings.cleartextKeyWarning"] = "이 엔드포인트는 평문 HTTP를 씁니다 — API 키가 암호화 없이 전송되어 같은 네트워크의 다른 사람이 볼 수 있습니다.",
        ["settings.systemPrompt"] = "시스템 프롬프트",
        ["settings.profile"] = "프로필",
        ["settings.add"] = "추가",
        ["settings.rename"] = "이름변경",
        ["settings.delete"] = "삭제",
        ["settings.newProfile"] = "새 프로필",
        ["settings.defaultProfile"] = "기본",
        ["settings.profileName"] = "프로필 이름",
        ["settings.hotkey"] = "핫키",
        ["settings.recordingKeys"] = "키 입력 대기…",
        ["settings.record"] = "녹화",
        ["settings.system"] = "시스템",
        ["settings.launchAtLogin"] = "로그인 시 시작",
        ["common.ok"] = "확인",
        ["common.cancel"] = "취소",
        ["error.invalidBaseURL"] = "Base URL이 올바르지 않습니다: {0}",
        ["error.httpFailure"] = "LLM 요청 실패 (HTTP {0}): {1}",
        ["error.invalidResponse"] = "잘못된 응답",
        ["error.unknown"] = "알 수 없는 오류",
        ["error.truncatedStream"] = "응답이 완료되기 전에 끊겼습니다.",
        ["app.secureFieldBlocked"] = "보안 필드 차단됨",
        ["hotkey.conflictTitle"] = "핫키를 쓸 수 없음",
        ["hotkey.conflictMessage"] = "그 키 조합은 이미 다른 앱이 사용 중입니다. 이전 핫키를 그대로 유지했습니다. 설정에서 다른 조합을 선택하세요.",
        ["menu.settings"] = "설정…",
        ["menu.build"] = "빌드 {0}",
        ["menu.quit"] = "종료",
    };
}
